<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))_NS</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="WpfAsservissementDisplay">
      <HintPath>obj\Debug\net8.0-windows\WpfAsservissementDisplay.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AsservissementRobot4RouesHoloDisplay.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
